# SETTINGS

# Remember more history
set-option -g history-limit 20000

# Longer key repeat time (2 seconds)
# Useful for pane resizing
set-option -g repeat-time 2000

# Use VIM keys in copy mode
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel 'tmux save-buffer - | pbcopy'

# Do this to enable VIM autoread
set-option -g focus-events on

# Fix colors
set-option -sa terminal-overrides ',xterm-256color:RGB'

# Start window numbers at 1 to match keyboard order with Tmux window order
set-option -g base-index 1
set-window-option -g pane-base-index 1

# Renumber windows sequentially after closing any of them
set-option -g renumber-windows on


# KEY BINDINGS

# Don't wait for ESC
set-option -s escape-time 0

# Use Ctrl-A as Prefix key
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

# Reload this config file with: Prefix + R
bind R source-file ~/.config/tmux/tmux.conf \; display '"~/.config/tmux/tmux.conf" reloaded'

# Managing the terminal window size
bind S new-window -d 'source ~/.config/zsh/.zshrc; terminal_window small; tmux list-panes -F "#F" | grep -q Z || tmux resize-pane -Z'
bind M new-window -d 'source ~/.config/zsh/.zshrc; terminal_window medium; tmux list-panes -F "#F" | grep -q Z || tmux resize-pane -Z'
bind B new-window -d 'source ~/.config/zsh/.zshrc; terminal_window large; tmux list-panes -F "#F" | grep -q Z && tmux resize-pane -Z'

# Enter copy mode with: Prefix + q
bind q copy-mode

# Pane movement shortcuts
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Move between windows like tabs
bind [ select-window -t :-
bind ] select-window -t :+

# Easier splits
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Resize pane shortcuts
bind -r H resize-pane -L 1
bind -r J resize-pane -D 1
bind -r K resize-pane -U 1
bind -r L resize-pane -R 1

# Set the width of the current pane to 90 (python black + 2 git status column)
bind W resize-pane -x 90

# Synchronize panes
bind C-x setw synchronize-panes

# COSMETICS

# Show the messages longer than the 750ms default
set-option -g display-time 4000

# Pane border style
set -g pane-border-style fg=colour251
set -g pane-active-border-style fg=colour81

# Status bar (hide it by default)
set-option -g status off
set-option -g status-interval 1
set-option -g status-left "#[fg=brightblack][#S] "
set-option -g status-left-length 20
set-option -g status-right "#[fg=brightgreen,bold]♫ #{track} #[fg=brightblack,none]#{artist} #[fg=white]| %a %h-%d %H:%M "
set-option -g status-right-length 80

# Default status bar colors
set-option -g status-style fg=white
set-window-option -g window-status-style fg=brightblack
set-window-option -g window-status-format " #I:#W"

# Active window title colors
set-window-option -g window-status-separator ''
set-window-option -g window-status-current-style fg=cyan
set-window-option -g window-status-current-format " #I:#[bold]#W"

# Message style
set-window-option -g message-style fg=gray,bg=default
